### ISSUE TITLE
Unsafe Constant Initialization

### ISSUE THREAD

**Issue by mahiuchun** [gazebosim/gz-math#269] opened 2021-10-15 21:50 UTC
In `ignition::math::Color` the color constants are defined like `public: static const Color Cyan;`. While the resulting interface is nice to use, it could cause static initialization order fiasco as C++ makes no guarantee that global variables in this form is going to be initialized in usage order. In other words, another global variable could use `Color::Cyan` and be initialized first.

A simple fix is to convert to a function form like the following:
`public: const Color& Cyan() { static auto *c = new Color(0, 1, 1, 1); return *c; }`

Another solution is more involved but it could retain the ability to refer to constants without parentheses.
1. Add a constexpr constructor to the class.
2. In another class, say, ColorConstants, use `public: static constexpr Color Cyan = {0, 1, 1, 1};`

Both solutions represent a API/ABI change, so I would like to hear some feedback first before sending out PRs.

The Vector classes might be affected by this too.

**Comment by jwnimmer-tri** [comment] 2021-11-22 18:35
> The Vector classes might be affected by this too.

Yes, I believe that `Vector3<T>::UnitX` etc. could all affected, at least in theory.  (Some compilers will optimize away the problematic portions, in practice.)

The full list of static const globals on the default branch seems to be: Angle, Color, Material, Matrix3, Matrix4, Pose3, Quaternion, Vector2, Vector3, Vector4.

Note that `Material::Predefined()` is particularly problematic, because it returns to the user a reference to `std::map`, which always implies a heap allocation and thus will always be leaked anytime the library is loaded and then unloaded.  Similarly for `kMaterialData` in `src/MaterialType.hh`.  Even if those collection types are fixed to be heapless, the `class Material` has a name which is required to always be on the heap.

Also note that both construction _and destruction_ order are in play here.  As library code, I'd argue that ign-math should have no global constructors nor global destructors registered at all.

For cross-reference, see also https://github.com/ignitionrobotics/sdformat/issues/552.

> A simple fix is ...

A third option (similar to the first option in the OP) would be use function-local static `std::aligned_storage`, which still keeps the data in static global storage, instead of on the heap.  Once example is Drake's [never_destroyed](https://github.com/RobotLocomotion/drake/blob/v0.36.0/common/never_destroyed.h) implementation.  This can be useful if the constructor is complicated enough that it cannot be made constexpr.  For this option as well as the first one, the function-local static requires the compiler to emit a lock guard instruction and storage for the boolean lock, so that the constant will be latch-initialized upon first use.  This is useful for complicated globals, but is overkill for the simple structs such as vector, color, quaternion, etc.

A fourth option (similar to the second option in the OP) is to keep the member fields static, but instead mark them constexpr at the _definition_.  See PR #283 for one example.  This is ABI-breaking but not API-breaking.

Therefore, my suggestion is to use:
- option (4) for the simple numeric constants (angle, vector3, vector4, pose, quaternion, color) as in PR #283;
- either option (1) or option (3) for any global data that is const but cannot be constexpr (material);

Hopefully, there are _no_ cases of _mutable_ global data.

**Comment by azeey** [comment] 2021-12-10 19:17
@scpeters, @mjcarroll, and I had a discussion and our preference is to use option (4) as in #283 for the simple numeric constants and option (3) for the rest. To that end, `NeverDestroyed` has been added to ign-utils in https://github.com/ignitionrobotics/ign-utils/pull/31.

**Comment by richmattes** [comment] 2022-01-25 04:25
> Note that `Material::Predefined()` is particularly problematic, because it returns to the user a reference to `std::map`, which always implies a heap allocation and thus will always be leaked anytime the library is loaded and then unloaded. Similarly for `kMaterialData` in `src/MaterialType.hh`. Even if those collection types are fixed to be heapless, the `class Material` has a name which is required to always be on the heap.

(Possibly) related to this - I'm seeing a unit test failure on Fedora rawhide where it appears that the `kMaterialData` map in `src/MaterialType.hh` isn't being properly initialized before being used in `src/Material.cc`.  The `UNIT_Material_TEST` fails with the following output (full log [here](https://download.copr.fedorainfracloud.org/results/@robotics-sig/gazebo-latest/fedora-rawhide-x86_64/03246876-ignition-math/build.log.gz)):

```
        Start  35: UNIT_Material_TEST
 34/102 Test  #35: UNIT_Material_TEST .....................***Failed    0.01 sec
Running main() from gtest_main.cc
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from MaterialTest
[ RUN      ] MaterialTest.Init
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:52: Failure
Expected: (mats.find(static_cast<MaterialType>(i))->second.Density()) > (0.0), actual: 0 vs 0
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:52: Failure
Expected: (mats.find(static_cast<MaterialType>(i))->second.Density()) > (0.0), actual: 0 vs 0
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:52: Failure
Expected: (mats.find(static_cast<MaterialType>(i))->second.Density()) > (0.0), actual: 0 vs 0
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:52: Failure
Expected: (mats.find(static_cast<MaterialType>(i))->second.Density()) > (0.0), actual: 0 vs 0
[  FAILED  ] MaterialTest.Init (0 ms)
[ RUN      ] MaterialTest.Comparison
[       OK ] MaterialTest.Comparison (0 ms)
[ RUN      ] MaterialTest.Accessors
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:95: Failure
Expected equality of these values:
  2700.0
    Which is: 2700
  mat.Density()
    Which is: 3.1620201333839779e-322
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:123: Failure
Expected equality of these values:
  MaterialType::TUNGSTEN
    Which is: 4-byte object <0C-00 00-00>
  material.Type()
    Which is: 4-byte object <00-00 00-00>
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:124: Failure
Expected equality of these values:
  19300.0
    Which is: 19300
  material.Density()
    Which is: 6.924653541527823e-310
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:136: Failure
Expected equality of these values:
  MaterialType::TUNGSTEN
    Which is: 4-byte object <0C-00 00-00>
  material.Type()
    Which is: 4-byte object <00-00 00-00>
/builddir/build/BUILD/ignition-math-6.9.2/src/Material_TEST.cc:137: Failure
Expected equality of these values:
  19300
  material.Density()
    Which is: 6.924653541527823e-310
[  FAILED  ] MaterialTest.Accessors (0 ms)
[----------] 3 tests from MaterialTest (0 ms total)
[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (0 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] MaterialTest.Init
[  FAILED  ] MaterialTest.Accessors
 2 FAILED TESTS
```

I did a little tracing/printing, and the `density` values for each of the `kMaterialData` map entries all contain garbage data when the `kMaterials` map is assembled in `src/Material.cc`.  I wasn't able to track down the root cause - it could be static initialization issues, or it could be a bug in gcc-12 which was just introduced into the Fedora buildroot.

If I modify the initialization of `kMaterialData` per [this patch](https://src.fedoraproject.org/rpms/ignition-math/blob/gazebo-latest/f/ignition-math-6.9.2-gcc12.patch), the density values are initialized correctly.

**Comment by jwnimmer-tri** [comment] 2022-01-25 14:30
FYI recently https://github.com/ignitionrobotics/ign-math/pull/290 fixed this issue (with respect to the Material map), for the `main` branch.

**Comment by richmattes** [comment] 2022-01-26 00:18
Thanks, I probably should have noticed that PR in the thread above...  I'm working on ign-math6 because gazebo-11 seems to be version locked to it, so I'll continue building the fedora package with my linked patch.  Feel free to pull it into ign-math6 if other distros start to have issues.

**Comment by scpeters** [comment] 2022-03-24 06:43
I see some new instances of potentially unsafe constant initialization in #388, #390, and #393. They almost follow the pattern of #283 but are not `constexpr`. Perhaps for these new classes, it would be better to define the static variables inside of a `const` method rather than as static member variables?

**Comment by azeey** [comment] 2023-10-05 21:22
I believe this was fixed by #283 and #290

**Comment by jwnimmer-tri** [comment] 2023-10-05 21:44
There are still some constructor+destructor fiascos:

```
./include/gz/math/graph/Vertex.hh:57:    public: static Vertex<V> NullVertex;
./include/gz/math/graph/Edge.hh:208:    public: static UndirectedEdge<E> NullEdge;
./include/gz/math/graph/Edge.hh:271:    public: static DirectedEdge<E> NullEdge;
```

There are still some destructor-only fiascos.  Hopefully the compiler optimizes it away, but I don't think its guaranteed:

```
./include/gz/math/Line2.hh:183:        static math::Vector2<T> ignore;
./include/gz/math/Line3.hh:266:        static math::Vector3<T> ignore;
```

**Comment by azeey** [comment] 2023-10-05 21:46
Thanks. I'll reopen it since we'll be bumping the major version of gz-math soon. It would be good to fix these then.

**Closed** 2024-07-15 18:41 UTC
Labels: bug, Breaking change

**Comment by scpeters** [comment] 2024-07-17 15:29
#606 has been reverted due to test failures in gz-sim
